### ISSUE TITLE
Fail to precompile Cuba

### ISSUE THREAD

**Issue by FiniteelementDuan** [giordano/Cuba.jl#18]
I have used the following code to install the Cuba package, and it works fine. 
```
julia> Pkg.update()
julia> Pkg.add("Cuba")
```
However, i got an error 'ERROR: Failed to precompile Cuba', when I use the following code:
```
using Cuba
```
What is the solution for this please?

I have a windows 10 system, and just installed Julia 1.0.

**Comment by giordano** [comment]
A few hours ago I've tagged a new version of `Cuba.jl` supporting Julia 0.7/1.0.  Waiting for https://github.com/JuliaLang/METADATA.jl/pull/16976 to be merged :wink:

**Comment by giordano** [comment]
In the meantime, you can switch to the `master` branch with:
```
] add Cuba#master
```

After the PR in METADATA is merged, you can go back to the stable version with
```
(v1.0) pkg> free Cuba

(v1.0) pkg> update
```

**Comment by FiniteelementDuan** [comment]
Ok. Many thanks!
