### ISSUE TITLE
Integration on general domains

### ISSUE THREAD

**Issue by arbenede** [giordano/Cuba.jl#20]
I am wondering if it possible to integrate an n-dimensional function on a set that is not an n-dimensional box in a way similar to the Monte Carlo integration routines in Numerical Recipes. If the function returns 0 when x is not in the set maybe this will just work in the current implementation of Cuba.jl?

**Comment by giordano** [comment]
I'm not sure I understand what you mean, could you please provide an example of what you would like to do? If you're asking for a way to integrate a domain different from the n-dimensional hypercube, then read the first "tip" box in the documentation: https://giordano.github.io/Cuba.jl/stable/

**Comment by arbenede** [comment]
Say that I want to integrate on a domain A that is not a hyper-rectangle (in my case A is a n-dimensional convex polytope but that does not really matter here). What I would do is to compute the smallest hyper-rectangle B such that A \in B and pass the bounds defined by B to Cuba. The function to be integrated would just return f(x) = 0 if x \in (B \ A). Do you think this would work?

**Comment by giordano** [comment]
If you are going to integrate a function on a domain larger than what you want, and define the integrand such that it returns zero outside the domain on which you actually want to integrate, yes, that would do the trick.

**Comment by giordano** [comment]
@arbenede did it solve your issue?

**Comment by arbenede** [comment]
Mose`, I did not have a chance to try this yet however I think that you can close this issue for now.

**Comment by giordano** [comment]
I'm going to close this issue, then.  Feel free to ping me here if you come across the same problem again
