### ISSUE TITLE
Run benchmark codes

### ISSUE THREAD

**Issue by ghost** [giordano/Cuba.jl#30]
Hi, Mosè. I have a problem in running the benchmark test on julia-1.5.2. 

I follow the instructions in the documentation (https://giordano.github.io/Cuba.jl/latest/#Performance-1).

After running "CUBACORES=0 julia -e 'using Pkg; import Cuba; include(joinpath(dirname(dirname(pathof(Cuba))), "benchmarks", "benchmark.jl"))'
" in Terminal, it returns

"
[ Info: Performance of Cuba.jl:
  0.383992 seconds (Vegas)
  0.572846 seconds (Suave)
  0.466027 seconds (Divonne)
  0.336353 seconds (Cuhre)
[ Info: Performance of Cuba Library in C:
ERROR: LoadError: UndefVarError: LIBPATH_env not defined
"

I have tried to run the benchmark code on MacOS and Debian. Both of them fail with the same error message. I guess it might be related to the fact that the benchmark code was written for Julia 0.7.0-beta2.3 as mentioned in the documentation. If possible, can you check this problem?

**Comment by giordano** [comment]
Should work now

**Comment by ghost** [comment]
It works! Thanks a lot!
