### ISSUE TITLE
change license to MIT?

### ISSUE THREAD

**Issue by StefanKarpinski** [giordano/Cuba.jl#40]
I was looking for LGPL packages, suspecting that there should not be many since for a Julia package there's no such thing as "linking" making LGPL equivalent to GPL. I found this package, which appears to be LGPL because it's a wrapper around an LGPL library (which is dynamically linked, so that makes sense). Wrapper code need not have the same license as the wrapped library, so this package could and arguably should be MIT licensed. As it stands, whereas Cuba can be used with/by non-open source software so long as modifications to Cuba are released in accordance with the LGPL, Cuba.jl cannot be used with/by non-open source software, which I don't think was the intention. Since there are still relatively few contributors, getting permission for a license change should be tractable.

**Comment by giordano** [comment]
Ok, let's do it.  There are only few contributors, all of them with only 1 commit, all with less than 10 lines, which the GNU project (typically strict in this regard) wouldn't even consider [legally significant](https://www.gnu.org/prep/maintain/html_node/Legally-Significant.html) for copyright purposes.

Current contributors:

- [ ] @yuyichao ([contributions](https://github.com/giordano/Cuba.jl/commits?author=yuyichao), not sure any of that is still there nowadays)
- [x] @staticfloat ([contributions](https://github.com/giordano/Cuba.jl/commits?author=staticfloat), no relevant changes nowadays)
- [x] @afniedermayer ([contributions](https://github.com/giordano/Cuba.jl/commits?author=afniedermayer), one line, but still used)
- [x] @mortenpi ([contributions](https://github.com/giordano/Cuba.jl/commits?author=mortenpi), not relevant anymore)
- [x] @JuliaTagBot ([contributions](https://github.com/giordano/Cuba.jl/commits?author=JuliaTagBot), largest external contributor, congrats!)

***If you've been tagged, do you agree to change the license terms of this package from LGPL to MIT?***

**Comment by staticfloat** [comment]
Yes, I agree

**Comment by mortenpi** [comment]
I agree as well. Although, in fairness, my contribution is non-substantial (automated PR bumping a version cap in CI config) and has since been removed, so I don't think I actually have any copyright claim here.

**Comment by afniedermayer** [comment]
I agree.

**Comment by kunyuan** [comment]
I agree as well.
